# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bible < Formula
  desc "A command line bible"
  homepage "https://github.com/Jmainguy/bible"
  version "0.0.1"
  license "GPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/bible/releases/download/v0.0.1/bible_Darwin_x86_64.tar.gz"
      sha256 "3f0b25d9f7faaac66e087a093934c727f93fb135e8c95bfc6f52f5f07de92b7c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/bible/releases/download/v0.0.1/bible_Linux_x86_64.tar.gz"
      sha256 "dec7ee96350b66de0f224fdb617a1ca89e9262e6e4e850cecb3d7b637fa6c46e"
    end
  end

  def install
    bin.install "bible"
  end

  test do
    system "#{bin}/bible"
  end
end
