# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Certificatedownloader < Formula
  desc "Download and trust certs"
  homepage "https://github.com/Jmainguy/certificateDownloader"
  version "0.1.4"
  license "GPL-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/certificatedownloader/releases/download/v0.1.4/certificatedownloader_Darwin_x86_64.tar.gz"
      sha256 "28a4b41de2bf982828b7e3eeac333e0e367a69a71befb61d85aa02777f6ace77"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/certificatedownloader/releases/download/v0.1.4/certificatedownloader_Linux_x86_64.tar.gz"
      sha256 "ef1d51b541b7c756bf179c35f713947d09f4d1c5d5d5980fb7ff148b28cf9e9b"
    end
  end

  def install
    bin.install "certificateDownloader"
  end

  test do
    system "#{bin}/certificateDownloader"
  end
end
