# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CertificateDownloader < Formula
  desc "Download and trust certs"
  homepage "https://github.com/Jmainguy/certificateDownloader"
  version "0.1.3"
  license "GPL-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/certificateDownloader/releases/download/v0.1.3/certificateDownloader_Darwin_x86_64.tar.gz"
      sha256 "80601371eac76b082cc30d3643dcc4016e37e3e3d958c3044e057e80e31e8b8b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/certificateDownloader/releases/download/v0.1.3/certificateDownloader_Linux_x86_64.tar.gz"
      sha256 "2be214c7179a5156d3fe7b9d32bf778564eb8b0aead846d94d190355e0ccfd2a"
    end
  end

  def install
    bin.install "certificateDownloader"
  end

  test do
    system "#{bin}/certificateDownloader"
  end
end
