# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Certificatedownloader < Formula
  desc "Download and trust certs"
  homepage "https://github.com/Jmainguy/certificatedownloader"
  version "0.1.3"
  license "GPL-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/certificatedownloader/releases/download/v0.1.3/certificatedownloader_Darwin_x86_64.tar.gz"
      sha256 "b18433e710209c8e5d55a5cf0d7e732ef9a721e2f4d4cb4ff69b44922dfc3d9c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/certificatedownloader/releases/download/v0.1.3/certificatedownloader_Linux_x86_64.tar.gz"
      sha256 "fdfed7aeadfef5c7d140c8d688f77fc7cb065a25bae99e53260ce1a753703eab"
    end
  end

  def install
    bin.install "certificatedownloader"
  end

  test do
    system "#{bin}/certificatedownloader"
  end
end
