# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Czechdns < Formula
  desc "A golang utility to check DNS records against expected results"
  homepage "https://github.com/Jmainguy/czechdns"
  version "0.0.2"
  license "GPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/czechdns/releases/download/v0.0.2/czechdns_Darwin_x86_64.tar.gz"
      sha256 "84ed7d1ca85cf64958ede4741ae275b1eb922feebf2a920cb49575a53ffd0da3"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/czechdns/releases/download/v0.0.2/czechdns_Linux_x86_64.tar.gz"
      sha256 "38f8755c333fce91c5749207f3b9ccf4e6c6b088683118aab29f442559f92a1c"
    end
  end

  def install
    bin.install "czechdns"
  end

  test do
    system "#{bin}/czechdns"
  end
end
