# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ggth < Formula
  desc "Golang Github Template Helper"
  homepage "https://github.com/Jmainguy/ggth"
  version "0.0.0"
  license "GPL-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/ggth/releases/download/v0.0.0/ggth_Darwin_x86_64.tar.gz"
      sha256 "9fb638f71cb0a1b6575a0742fae05dfa31cad8d276c3ca14383237e3ac2a6ec0"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/ggth/releases/download/v0.0.0/ggth_Linux_x86_64.tar.gz"
      sha256 "fa42d12885d7af465c735a6144a505ce5f4f18f19742d3be5f657229bdca5066"
    end
  end

  def install
    bin.install "ggth"
  end

  test do
    system "#{bin}/ggth"
  end
end
