# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghdefaultbranch < Formula
  desc "Check Github for Pull Requests, that are not Drafts, in repos the user cares about."
  homepage "https://github.com/Jmainguy/ghdefaultbranch"
  version "0.0.0"
  license "GPL-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/ghdefaultbranch/releases/download/v0.0.0/ghdefaultbranch_Darwin_x86_64.tar.gz"
      sha256 "dbe5d04b1aee49241acab81b108f6f613f6e5c6b5b6a6726ece96736f347ac1c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/ghdefaultbranch/releases/download/v0.0.0/ghdefaultbranch_Linux_x86_64.tar.gz"
      sha256 "d11af6252e0acc5e3cffb8b610ef4424730255d7c53b12de88d8756830721c00"
    end
  end

  def install
    bin.install "ghdefaultbranch"
  end

  test do
    system "#{bin}/ghdefaultbranch"
  end
end
