# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghreport < Formula
  desc "Check Github for Pull Requests, that are not Drafts, in repos the user cares about."
  homepage "https://github.com/Jmainguy/ghreport"
  version "0.0.1"
  license "GPL-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Jmainguy/ghreport/releases/download/v0.0.1/ghreport_Darwin_arm64.tar.gz"
      sha256 "bd2a5c7f0c91a73629abde2b1457e14034d6a1c08726fda2a2c4a9082851df77"

      def install
        bin.install "ghreport"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/ghreport/releases/download/v0.0.1/ghreport_Darwin_x86_64.tar.gz"
      sha256 "64431dd40020555f53cfbb19e2b7a1a7b0cba60d5f1e1f71a55f971f8fb9b2d4"

      def install
        bin.install "ghreport"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/ghreport/releases/download/v0.0.1/ghreport_Linux_x86_64.tar.gz"
      sha256 "85e4686e1e966be339f64d1fe88ada408bc314795d3659725b8db52ee3dadcdd"

      def install
        bin.install "ghreport"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jmainguy/ghreport/releases/download/v0.0.1/ghreport_Linux_arm64.tar.gz"
      sha256 "28b9a503c03e2378570a2400ca0eba57a9037bab3056f2e3f53bed8671025876"

      def install
        bin.install "ghreport"
      end
    end
  end

  test do
    system "#{bin}/ghreport"
  end
end
