# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Githubstats < Formula
  desc "A golang application to return stats from github via their graphql endpoint"
  homepage "https://github.com/Jmainguy/githubstats"
  version "0.0.0"
  license "GPL-2.0"

  on_macos do
    url "https://github.com/Jmainguy/githubstats/releases/download/v0.0.0/githubstats_Darwin_x86_64.tar.gz"
    sha256 "d1ceade4e51cf6ae0d382f737e81f5df85044b49129b5c8bb8e653448dc49aa8"

    def install
      bin.install "githubstats"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Githubstats
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/githubstats/releases/download/v0.0.0/githubstats_Linux_x86_64.tar.gz"
      sha256 "b9935808dc33bee037571f06d12ce1f095ba957f2418e2fa5eede6fde4aaa303"

      def install
        bin.install "githubstats"
      end
    end
  end

  test do
    system "#{bin}/githubstats"
  end
end
