# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gohome < Formula
  desc "Dynamic DNS using nsd and ssh"
  homepage "https://github.com/Jmainguy/gohome"
  version "0.0.0"
  license "GPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/gohome/releases/download/v0.0.0/gohome_Darwin_x86_64.tar.gz"
      sha256 "d4a5aaed0d65ee50388af0bbf93db1dda89d472ef13a1ecfc905a8b708f599b1"

      def install
        bin.install "gohome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jmainguy/gohome/releases/download/v0.0.0/gohome_Linux_arm64.tar.gz"
      sha256 "d31c25076f30598b53b94db2f895dae8c5d312ae5dde4f9c51c01a232e6c993b"

      def install
        bin.install "gohome"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/gohome/releases/download/v0.0.0/gohome_Linux_x86_64.tar.gz"
      sha256 "c14d35b75e6a4f393afbfeb69e1b4cfec38e3a3c2f6a5e9d0c13b52790da1aa5"

      def install
        bin.install "gohome"
      end
    end
  end

  test do
    system "#{bin}/gohome"
  end
end
