# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Indent < Formula
  desc "Ident from a file to stdout using spaces"
  homepage "https://github.com/Jmainguy/indent"
  version "0.0.1"
  license "GPL-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/indent/releases/download/v0.0.1/indent_Darwin_x86_64.tar.gz"
      sha256 "6d4cde4c52ac587a699960853725162a84d03dc79c2c70473aedc7b2887ac35d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/indent/releases/download/v0.0.1/indent_Linux_x86_64.tar.gz"
      sha256 "ac84903cc498bfd716d218d52245a6f6c583ef3f8dd8921664f5048391e8e340"
    end
  end

  def install
    bin.install "indent"
  end

  test do
    system "#{bin}/indent"
  end
end
