# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8snodeissues < Formula
  desc "Designed to point out potential issues in a kubernetes node. Such as pods stuck terminating, or pending."
  homepage "https://github.com/Jmainguy/k8snodeissues"
  version "0.1.1"
  license "GPL-2.0"

  on_macos do
    url "https://github.com/Jmainguy/k8snodeissues/releases/download/v0.1.1/k8snodeissues_Darwin_x86_64.tar.gz"
    sha256 "c2f8901e1eeb969a6b2df695eb307e76dbd088d4e2241f5991ccbedb35bc6629"

    def install
      bin.install "k8snodeissues"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the K8snodeissues
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/k8snodeissues/releases/download/v0.1.1/k8snodeissues_Linux_x86_64.tar.gz"
      sha256 "c0dd8e58bb161493b0405278cc0c405435fa67dcb05a5c8b879a7ca12cca0685"

      def install
        bin.install "k8snodeissues"
      end
    end
  end

  test do
    system "#{bin}/k8snodeissues"
  end
end
