# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Servmon < Formula
  desc "A service monitor written in go"
  homepage "https://github.com/Jmainguy/servmon"
  version "0.0.0"
  license "GPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/servmon/releases/download/v0.0.0/servmon_Darwin_x86_64.tar.gz"
      sha256 "d190ee0c454427eb566a295190a10bcd4bc4e1b27973d99ef3b717e57bc87570"

      def install
        bin.install "servmon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Jmainguy/servmon/releases/download/v0.0.0/servmon_Darwin_arm64.tar.gz"
      sha256 "1c7a4caa6c8ad49742d33078ba68d2c4710b8006c70bf1a259b51dd550073b72"

      def install
        bin.install "servmon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jmainguy/servmon/releases/download/v0.0.0/servmon_Linux_arm64.tar.gz"
      sha256 "4ab9d388f7d48df05d9273bd716462ba2519361b37628e9972ae6e32f45527bd"

      def install
        bin.install "servmon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/servmon/releases/download/v0.0.0/servmon_Linux_x86_64.tar.gz"
      sha256 "0462d0caaa7c29050d158e9f681ee0c16fbbe29dbed5b867710b935dbc3b62dd"

      def install
        bin.install "servmon"
      end
    end
  end

  test do
    system "#{bin}/servmon"
  end
end
