# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Servmon < Formula
  desc "A service monitor written in go"
  homepage "https://github.com/Jmainguy/servmon"
  version "0.0.0"
  license "GPL-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Jmainguy/servmon/releases/download/v0.0.0/servmon_Darwin_arm64.tar.gz"
      sha256 "2655e56a2373ed88027d9f463c261814fb99d148228cb4db34f32b59ec905cfe"

      def install
        bin.install "servmon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/servmon/releases/download/v0.0.0/servmon_Darwin_x86_64.tar.gz"
      sha256 "629e4ff950cf72d36328cb1f3d06d3cf098bc842fa29640917636da0ec2f30c7"

      def install
        bin.install "servmon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jmainguy/servmon/releases/download/v0.0.0/servmon_Linux_arm64.tar.gz"
      sha256 "36bc74849001d485870e20e638b476b7ae094c3787b7929d1b4bc71a97c8fe43"

      def install
        bin.install "servmon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Jmainguy/servmon/releases/download/v0.0.0/servmon_Linux_x86_64.tar.gz"
      sha256 "1f419fa02c25c8cbf16b34d4b1dace031e585a81d99eca76fa4ae7e478b63e6a"

      def install
        bin.install "servmon"
      end
    end
  end

  test do
    system "#{bin}/servmon"
  end
end
